<?php
namespace competence\models\test\mailru2016_prof;

class A9_3 extends \competence\models\form\Multiple
{
    public function __get($name)
    {
        if ($name === 'Values') {
            $values = parent::__get($name);

            $end = array_slice($values, -3);
            return array_merge(
                $this->rotate('A9_3_val', array_slice($values, 0, count($values) - 3)),
                $end
            );
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }
}
