<h3>Здравствуйте <?=$user->getShortName()?>!</h3>

<p>Ассоциация электронных коммуникаций (НП&nbsp;«РАЭК»), Координационный центр национального домена сети Интернет и&nbsp;сообщество разработчиков и&nbsp;пользователей PostgreSQL приглашают Вас принять участие в&nbsp;первом общероссийском форуме <a href="http://pgconf.ru/">PGCONF.RUSSIA 2015</a> посвященном свободно распространяемой СУБД PostgreSQL, которая состоится <nobr>6-8</nobr> февраля 2015 года в&nbsp;конференц-центре Digital October. </p>
<p style="margin-top: 10px 0; text-align: center;">
    <a href="<?=$user->getFastauthUrl('http://runet-id.com/event/pgcr15/')?>" style="font-size: 100%; color: #FFF; text-decoration: none; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: uppercase; background-color: #348eda; margin: 0 10px 0 0; padding: 0; border-color: #348eda; border-style: solid; border-width: 10px 40px;">Зарегистрироваться</a>
</p>
<p><b>PostgreSQL</b>&nbsp;— это свободно распространяемая объектно-реляционная система управления базами данных (ORDBMS), наиболее развитая из&nbsp;открытых СУБД в&nbsp;мире и&nbsp;являющаяся реальной альтернативой коммерческим базам данных. PostgreSQL обеспечивает высокий подтвержденный опытом уровень надежности, расширяемости, сохранности данных и&nbsp;качественную поддержку со&nbsp;стороны сообщества.</p>
<p><b>Цель форума</b>&nbsp;— собрать вместе представителей бизнес-сообщества, ИТ-директоров, разработчиков, пользователей и&nbsp;администраторов PostgreSQL, а&nbsp;также представителей государственных органов и&nbsp;компаний, стоящих перед выбором платформы. Государство и&nbsp;бизнес должны увидеть зрелость сообщества PostgreSQL и&nbsp;его способность решать сложнейшие задачи. На&nbsp;форуме будут обсуждаться альтернативы коммерческим продуктам в&nbsp;системах, важных для государства и&nbsp;бизнеса, возможность использования свободно-распространяемых продуктов в&nbsp;критически важных приложениях.</p>
<p><b>Крупные коммерческие компании уже активно используют PostgreSQL</b> и&nbsp;строят свой бизнес на&nbsp;его основе. С&nbsp;их&nbsp;опытом вы&nbsp;сможете ознакомиться в&nbsp;рамках <a href="http://pgconf.ru/papers">программы конференции</a>. </p>
<p>Организационный комитет форума приглашает вас к&nbsp;участию, сегодня с&nbsp;нами представители крупнейших бизнес структур и&nbsp;государственный органиазций, разработчики системы и&nbsp;специалисты по&nbsp;внедрению и&nbsp;миграции! </p>
<p style="margin-top: 10px 0; text-align: center;">
    <a href="<?=$user->getFastauthUrl('http://runet-id.com/event/pgcr15/')?>" style="font-size: 100%; color: #FFF; text-decoration: none; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: uppercase; background-color: #348eda; margin: 0 10px 0 0; padding: 0; border-color: #348eda; border-style: solid; border-width: 10px 40px;">Зарегистрироваться</a>
</p>
<p align="center"><strong>Надеемся, что и&nbsp;вы&nbsp;будете с&nbsp;нами.</strong></p>