<?php
$regLink = "http://2014.russianinternetweek.ru/my/?RUNETID=" . $user->RunetId . "&KEY=" . substr(md5($user->RunetId.'vyeavbdanfivabfdeypwgruqe'), 0, 16);
?>

<!-- Inliner Build Version 4380b7741bb759d6cb997545f3add21ad48f010b -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>RIW 2014</title>
  </head>
  <body bgcolor="#ffffff" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; margin: 0; padding: 0;">

<!-- body -->
<table class="body-wrap" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; width: 100%; margin: 0; padding: 20px;"><tr style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><td style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"></td>
		<td class="container" bgcolor="#FFFFFF" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 0 20px 20px; border: 0;">
			<!-- content -->
			<div class="content" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; max-width: 600px; display: block; margin: 0 auto; padding: 0;">
			<table style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; width: 100%; margin: 0; padding: 0;"><tr style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><td style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">
						<table style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; width: 100%; margin: 0; padding: 0;"><tr style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><td style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">
									<h3 style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.2; color: #000; font-weight: 200; margin: 40px 0 10px; padding: 0;"><?=$user->getShortName()?>, здравствуйте!</h3>
									<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 30px; padding: 0;"><b style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">Приглашаем Вас принять участие в RIW 2014:<br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />ПОСЕТИТЬ ВЫСТАВКУ<br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />ПРИНЯТЬ УЧАСТИЕ В КОНФЕРЕНЦИИ</b></p>
								</td>
								<td align="right" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><img src="http://getlogo.org/img/riw/727/150x/" alt="RIW" title="RIW" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; max-width: 100%; margin: 0; padding: 0;" /></td>
							</tr></table><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 30px; padding: 0;"><big style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.4; margin: 0; padding: 0;">RIW 2014 —</big><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />пройдет 12—13—14 ноября 2014 года в московском Экспоцентре на Красной Пресне — <a href="http://www.riw.moscow" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; color: #348eda; margin: 0; padding: 0;">www.RIW.moscow</a> </p>
						<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><big style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.4; margin: 0; padding: 0;">RIW 2014 — Russian Interactive Week —</big><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />это главное осеннее мероприятие сразу нескольких отраслей: Интернет, Медиа и Телеком. </p>
						<h3 style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.2; color: #000; font-weight: 200; margin: 40px 0 10px; padding: 0;">RIW 2014 — это: </h3>
						<ul style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><li style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0 0 15px 35px; padding: 0;"><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><b style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">Выставка «ИНТЕРНЕТ 2014»</b><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Компании со стендами по направлениям: интернет-бизнес, телеком, гаджеты, медиахолдинги, решения для пользователей и b2b-решения </p></li>
							<li style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0 0 15px 35px; padding: 0;"><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><b style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">Медиа-Коммуникационный Форум</b><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Конференционная программа из более чем 10 блок-конференций: <br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Реклама; Маркетинг; Медиаконтент; Мобильные технологии, платформы и решения; Веб-разработка; Social Media; Электронная коммерция; Кадры для отрасли; Госрегулирование; Информационная безопасность; Инвестиции и стартапы; Веб-аналитика </p></li>
							<li style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0 0 15px 35px; padding: 0;"><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><b style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">UpStart Conf</b><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Конференция для стартапов, моложых команд и предпринимателей, инвесторов и бизнес-ангелов </p></li>
							<li style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0 0 15px 35px; padding: 0;"><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><b style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">Аллея инноваций</b><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Стенды молодых проектов и стартапов, на которых будут представлены 45 финалистов конкурсного отбора</p></li>
							<li style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0 0 15px 35px; padding: 0;"><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><b style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">Внепрограммные мероприятия</b><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Серия вечерних мероприятий RIW-night, множество профессиональных конкурсов и наград: Облака 2014, Блог Рунета, Золотой сайт, IMA и др.</p></li>
						 </ul><h3 style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.2; color: #000; font-weight: 200; margin: 40px 0 10px; padding: 0;">Аудитория RIW 2014:</h3>
						<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;">В RIW 2014 примут участие представители крупнейших интернет-компаний, телеком-операторов и медиахолдингов, лидеры российского интернет-бизнеса, эксперты и специалисты по инфокоммуникациям и интернет-технологиям, а также представители профильных министерств и ведомств — за три дня работы RIW 2014 они обсудят все основные тренды развития отрасли, объединяющей телеком, медиа и интернет. </p>
						<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;">В конференционной программе RIW 2014 примут участие более 4 тыс. профессиональных участников (специалисты телеком-отрасли, интернет-рынка и медиа-сегмента). Общее количество докладчиков превысит 600 человек.</p>
						<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;">Большой популярностью среди интернет-пользователй, интернет-специалистов и всех, кто интересуется высокими технологиями — будет пользоваться Выставка RIW 2014. По прогнозам Оргкомитета, за три дня работы Выставку посетят более 20 тыс. участников. Со стендами в выставке примут участие более 200 компаний-экспонентов.</p>
						<h3 class="center" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.2; text-align: center; color: #000; font-weight: 200; margin: 40px 0 10px; padding: 0;" align="center">Приглашаем Вас принять участие в RIW 2014!</h3>
						<div class="frame" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; text-align: center; margin: 25px 0 0; padding: 25px 40px 15px; border: 2px dashed #000;" align="center">
							<h4 style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">Возможные форматы участия:</h4>
							<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"></p><h2 style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 28px; line-height: 1.2; color: #000; font-weight: 200; margin: 40px 0 10px; padding: 0;">Посетитель Выставки</h2>(бесплатно все три дня: <nobr style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">12-14 ноября)</nobr><p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"></p><h2 style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 28px; line-height: 1.2; color: #000; font-weight: 200; margin: 40px 0 10px; padding: 0;">Участник<br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Профессиональной программы</h2>(при оплате регистрационного взноса)
							<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 25px 0 10px; padding: 0;">Участие возможно только после РЕГИСТРАЦИИ на сайте мероприятия. </p>
							<p style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 0 0 10px; padding: 0;"><big style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 22px; line-height: 1.4; margin: 0; padding: 0;"><a href="<?=$regLink?>" class="btn-link" style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; color: #348eda; border-bottom-style: dashed; border-bottom-width: 1px; font-weight: 900; text-decoration: none; margin: 0; padding: 0;">БЫСТРАЯ РЕГИСТРАЦИЯ</a></big><br style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />(ваша персональная ссылка)</p>
						</div>
					</td>
				</tr></table></div>
			<!-- /content -->

		</td>
		<td style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"></td>
	</tr></table><!-- /body --></body>
</html>
