<?php
$regLink = "http://riw.moscow/my/?RUNETID=" . $user->RunetId . "&KEY=" . substr(md5($user->RunetId.'vyeavbdanfivabfdeypwgruqe'), 0, 16);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns="http://www.w3.org/1999/xhtml" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Главное страновое событие отрасли высоких технологий — Russian Interactive Week — пройдет 21–23 октября 2015 года, в Московском Экспоцентре на Красной Пресне.</title>
  </head>
  <body bgcolor="#246E9C" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none; width: 100% !important; height: 100%; background: #246E9C; margin: 0; padding: 0;"><style type="text/css">
@media (max-width: 400px) {
  .chunk {
    width: 100% !important;
  }
}
</style>

<!-- body -->
<table class="body-wrap" bgcolor="#246E9C" style="background: #246E9C; font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; width: 100%; margin: 0; padding: 20px;"><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"></td>
		<td class="container" bgcolor="#246E9C" border="0" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; display: block !important; max-width: 600px !important; clear: both !important; background: #246E9C; margin: 0 auto; padding: 20px; border: 0 solid #f0f0f0;">
			<!-- header -->
			<br style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" /><img src="http://showtime.s3.amazonaws.com/20150708134050_-_RIW_2015_Russian_Interactive_Week_2015__glavnoe_osennee_meropriyatie_treh_otraslei_Internet_Media_Telekom_-_rgxxu.jpg" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; height: auto; max-width: 100%; margin: 0; padding: 0;" /><br style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" /></td>
		<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"></td>
	</tr><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"></td>
		<td class="container" bgcolor="#FFFFFF" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; display: block !important; max-width: 600px !important; clear: both !important; margin: 0 auto; padding: 20px; border: 1px solid #f0f0f0;">
			<!-- content -->
			<div class="content" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; max-width: 600px; display: block; margin: 0 auto; padding: 0;">
			<table style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; width: 100%; margin: 0; padding: 0;"><tr style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"><td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">
						<h3 style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 22px; line-height: 1.2; color: #000; font-weight: 200; margin: 0 0 10px; padding: 0;"><?=$user->getShortName()?>,<br style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />Время летит очень быстро!</h3>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">RIW 2015 – главное осеннее мероприятие отрасли высоких технологий – пройдет 21-23 октября 2015 года в Экспоцентре — <a href="http://www.riw.moscow" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; color: #348eda; margin: 0; padding: 0;">www.RIW.moscow</a></p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">RIW объявляет о главных акцентах августа, которые нельзя упустить из вида:</p>
						<h4 style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 22px; line-height: 1.1; color: #000; font-weight: 200; margin: 0 0 10px; padding: 0;">1. Стать участником!</h4>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">RIW 2015 – главная IT-выставка России, мощная конференционная программа и множестве специальных мероприятий и проектов, включая RIW.Nigth.</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Стать участником RIW 2015 и получить доступ ко всему этому контенту – можно бесплатно, в один клик (если Вы уже зарегистрированы на RIW, Вы можете также зарегистрировать Ваших коллег, воспользовавшись ссылкой ниже:</p>
						<div class="frame center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; text-align: center; margin: 25px 0; padding: 0;" align="center">
							<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">
								<a href="<?=$regLink?>" class="btn-primary" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.2; color: #FFF; text-decoration: none; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: uppercase; background: #FA2045; margin: 0 10px 0 0; padding: 0; border-color: #fa2045; border-style: solid; border-width: 10px 25px 15px;"><big style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 22px; line-height: 1.4; font-weight: 200; margin: 0; padding: 0;"><b style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">РЕГИСТРАЦИЯ НА ВЫСТАВКУ</b></big><br style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />(персональная ссылка)</a>
							</p>
						</div>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Все зарегистрированные участники RIW 2015 имеют доступ на Выставку “Интернет 2015”, Softool 2015 (где можно познакомиться с продуктамии, услугами и новыми интернет-проектами ведущих и молодых IT-компаний, игроков телеко-сегмента, оразработчиков ПО и медиа-холдингов).</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">RIW – это также презентации и эксклюзивные выступления, которые пройдут в режиме нон-стоп в течение 3 дней в Presentation Hall. И мощная конференционная программа, главным залом которой будет White Hall.</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Все зарегистрированные участники RIW 2015 – имеют доступ в <strong>Presentation Hall</strong> (главный зал презентаций), <strong>White Hall</strong> (главный конференционный зал), а также в зону <strong>“Аллея инноваций”</strong>, на многие специальные стенды и в партнерские зоны RIW 2015.</p>
                        <div class="frame center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; text-align: center; border-bottom-width: 1px; border-bottom-color: #F6F6F6; border-bottom-style: solid; height: 1px; margin-bottom: 20px;" align="center"></div>
                        <h4 style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 22px; line-height: 1.1; color: #000; font-weight: 200; margin: 0 0 10px; padding: 0;">2. Стать профессиональным участником: в августе – по специальной цене! </h4>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Воспользоваться спецпредложением и стать <strong>профессиональным участником RIW 2015</strong> – можно всегда, но в августе это особенно выгодно, так как до конца месяца действует специальная цена регистрации участия в Проф. программе: 6000 рублей за все дни работы RIW, включая налоги.</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Профессиональная программа – это огромный объем уникального контента:</p>
						<ul>
							<li style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; margin: 0 0 5px; padding: 0;"><strong>9 больших конференц-залов</strong> (т.н. цветные залы), которые будут работать параллельно все дни проведения RIW;</li>
							<li style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; margin: 0 0 5px; padding: 0;"><strong>более 20 блок-конференций</strong> по всем темам отрасли высоких технологий (интернет, софт, медиа, телеком), интересные специалистам, менеджерам, клиентам, пользователям;</li>
							<li style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; margin: 0 0 5px; padding: 0;"><strong>более 500 докладчиков</strong> – все гуру и ключевые спикеры отрасли;</li>
							<li style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; font-weight: normal; margin: 0 0 5px; padding: 0;"><strong>более 4000 профессиональных участников.</strong></li>
						</ul>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Доступ ко всему этому контенту – <strong>неограничен</strong> для профессиональных участников все три дня, а по итогам RIW 2015 им будет предоставлены <strong>итоговые материалы и презентации докладчиков</strong>.</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Также профессиональные участники имеют неограниченный доступ в комфортную <strong>Бизнес-зону</strong> – идеальное место для установления деловых контактов и проведения бизнес-встреч, для кофе-брейков и для просмотра онлайн-трансляций из конференционных залов RIW 2015.</p>

						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;"><strong>ВНИМАНИЕ!</strong><br/>
							Только до конца августа Вы можете зарегистрироваться самостоятельно и/или зарегистрировать Ваших коллег – в статусе профессионального участника – по специальной цене 6000 руб., включая все налоги!</p>
                        <div class="frame center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; text-align: center; border-bottom-width: 1px; border-bottom-color: #F6F6F6; border-bottom-style: solid; margin: 25px 0; padding: 0;" align="center">
							<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">
								<a href="<?=$regLink?>" class="btn-primary" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.2; color: #FFF; text-decoration: none; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: uppercase; background: #FA2045; margin: 0 10px 0 0; padding: 0; border-color: #fa2045; border-style: solid; border-width: 10px 25px 15px;"><big style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 22px; line-height: 1.4; font-weight: 200; margin: 0; padding: 0;"><b style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">РЕГИСТРАЦИЯ ПРОФ.УЧАСТИЯ – В ОДИН КЛИК</b></big><br style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />(персональная ссылка)</a>
							</p>
						</div>
						<h4 style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 22px; line-height: 1.1; color: #000; font-weight: 200; margin: 0 0 10px; padding: 0;">3. Стать докладчиком! </h4>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Если Вы обладаете уникальным контентом, который может быть интересен и полезен посетителям и профессиональным участникам RIW 2015 – Вы можете заявить о своем желании стать докладчиком проекта.</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Для подачи заявки на выступление, рекомендуем ознакомится с правилами для докладчиков и ведущих секций – http://riw.moscow/forum/requirements/</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Программа Russian Interactive Week 2015 формируется Программным комитетом, и в этом году насчитывает 9 параллельных потоков.</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">При разработке программы RIW 2015 производится жесткая привязка докладов, секций, круглых столов и целых блок-конференций — к одной из  Экосистем Рунета (основополагающий каталог тем развития интернета и его рыночных сегментов)</p>
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">При подаче заявки – выберите Экосистему, наиболее подходящую по тематике вашего выступления. После проверки оргкомитетом, доклад будет предложен к рассмотрению организаторам секций относящихся к этой Экосистеме.</p>
                        <div class="frame center" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; text-align: center; border-bottom-width: 1px; border-bottom-color: #F6F6F6; border-bottom-style: solid; margin: 25px 0; padding: 0;" align="center">
                            <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">
                                <a href="http://riw.moscow/program/add/" class="btn-primary" style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.2; color: #FFF; text-decoration: none; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: uppercase; background: #298bb0; margin: 0 10px 0 0; padding: 0; border-color: #298bb0; border-style: solid; border-width: 10px 25px 15px;"><big style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 22px; line-height: 1.4; font-weight: 200; margin: 0; padding: 0;"><b style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;">ПОДАТЬ ЗАЯВКУ НА ДОКЛАД</b></big><br style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;" />В РАМКАХ RIW 2015</a>
                            </p>
                        </div>
                        <h4 style="font-family: 'Helvetica Neue', Helvetica, Arial, 'Lucida Grande', sans-serif; font-size: 22px; line-height: 1.1; color: #000; font-weight: 200; margin: 0 0 10px; padding: 0;">4. Стать партнером и экспонентом!</h4>
                        <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">RIW 2015 и Выставка “ИНТЕРНЕТ 2015” — идеальные площадка для установления деловых контактов, проведения переговоров и демонстраций.</p>
                        <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Это место встреч, коммуникаций, обмена опытом и демонстрации достижений российской отрасли высоких технологий и инноваций (интернет, телеком, медиа). Выставка — это также площадка для диалога отрасли с государством и уникальный формат самопрезентации для новых IT-проектов, предпринимателей и молодых команд.</p>
                        <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Подробная <a href="http://riw.moscow/expo/scheme/" target="_blank">схема Выставки</a> и <a href="http://riw.moscow/expo/exponents/" target="_blank">перечнь компаний-экспонентов</a>.</p>
                        <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Посещение Выставки — бесплатное для всех зарегистрированных участников ожидается более 25000 посетителей за 3 дня работы RIW 2015).</p>
                        <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 15px 0 20px; padding: 0;">Разместить свой стенд на выставке – может партнер (экспонент) RIW 2015, одобренный Оргкомитетом. Условия участия в Выставке, стоимость аренды выставочной площади, застройки стенда и дополнительных опций — по запросу: <a href="mailto:partners@russianinternetweek.ru">partners@russianinternetweek.ru</a></p>
                        <p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 30px 0 20px; padding: 0;">Не упустите эти уникальные предложения и специальные условия августа, и до встречи на RIW 2015!  </p>
                        <img src="http://runet-id.com/img/mail/2015/20150824_riw15.jpg" />
						<p style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 14px; line-height: 1.6; font-weight: normal; margin: 30px 0 20px; padding: 0;">
                            ---------------------------<Br/>
                            С уважением,<br/>
                            Оргкомитет RIW 2015<br/>
                            <a href="mailto:users@russianinternetweek.ru">users@russianinternetweek.ru</a><br/>
                        </p>
                    </td>
				</tr></table></div>
			<!-- /content -->

		</td>
		<td style="font-family: 'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif; font-size: 100%; line-height: 1.6; margin: 0; padding: 0;"></td>
	</tr></table><!-- /body --></body>
</html>
