<p><img src="https://showtime.s3.amazonaws.com/201703302334-iior17_mail-banner.jpg" style="height: auto; width: 100%;"></p>
<h3>Здравствуйте, <?=$user->getShortName()?>!</h3>
<p>Региональная общественная организация «Центр интернет-технологий» (<a href="http://www.rocit.ru">РОЦИТ</a>) проводит опрос экспертов Республики Татарстан с&nbsp;целью формирования «Индекса интернет-открытости регионов России».</p>
<p>Результаты этого передового проекта позволят сделать выводы об&nbsp;открытости взаимодействия государства и&nbsp;бизнеса в&nbsp;интернет-пространстве, а&nbsp;также продемонстрировать ключевые болевые точки и&nbsp;пути их&nbsp;устранения для всех субъектов Российской Федерации. </p>
<p><b>Ваше участие очень важно для нас</b>, ведь только посредством совместного диалога мы&nbsp;сможем максимально эффективно решить существующие проблемы как отдельных регионов, так и&nbsp;государства в&nbsp;целом.</p>
<p>Опрос носит анонимный характер и&nbsp;займет не&nbsp;более 15&nbsp;минут, все полученные данные будут использоваться только в&nbsp;обобщенном виде.</p>
<p style="margin-top: 10px 0; text-align: center;">
	<a href="<?=$user->getFastauthUrl('/competence/main/index/?id=55')?>&utm_source=runet-id.com&utm_medium=email&utm_campaign=1321" style="font-size: 100%; color: #FFF; text-decoration: none; font-weight: bold; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; text-transform: uppercase; background-color: #D04727; margin: 0 10px 0 0; padding: 0; border-color: #D04727; border-style: solid; border-width: 10px 40px;">Перейти к опросу »</a>
	<div style="font-size: 90%; text-align: center; color: #444;">Благодарим Вас за&nbsp;согласие принять участие в&nbsp;исследовании!</div>
</p>
<p>Первые результаты будут презентованы уже 7&nbsp;апреля 2017&nbsp;г.&nbsp;на&nbsp;8&nbsp;Российском форуме по&nbsp;управлению интернетом <a href="http://rigf.ru/">RIGF 2017</a>&nbsp;в Иннополисе. Развернутая презентация исследования состоится <nobr>24-25</nobr> мая 2017&nbsp;г.&nbsp;на&nbsp;форуме РИФ.Иннополис.</p>
<p style="opacity: .7"><small>При реализации проекта используются средства государственной поддержки, выделенные в качестве гранта в соответствии c распоряжением Президента Российской Федерации от 05.04.2016 No 68-рп и на основании конкурса, проведенного Благотворительным фондом «ПОКРОВ».</small></p>