<?php
namespace application\components\form;

use application\components\helpers\ArrayHelper;
use application\helpers\Flash;
use \CActiveRecord;

abstract class CreateUpdateFormCombiner extends CreateUpdateForm
{
    /**
     * @inheritDoc
     */
    public function __construct(CActiveRecord $model = null)
    {
        $this->initForms();
        parent::__construct($model);
    }


    /** @var CreateUpdateForm[]  */
    private $forms = [];

    /**
     * Внутри метода инициализуируется дочерние формы
     * @return mixed
     */
    abstract protected function initForms();

    /**
     * Регистрация формы
     * @param string $name
     * @param array $args
     * @throws \Exception
     */
    protected final function registerForm($name, $args = [])
    {
        $reflect  = new \ReflectionClass($name);
        if ($reflect->getParentClass()->name === CreateUpdateForm::className()) {
            array_push($args, $this->model);
        }

        $form = $reflect->newInstanceArgs($args);
        if (!($form instanceof FormModel)) {
            throw new \Exception('Класс не является экземпляром классом \application\components\form\CreateUpdateForm');
        }
        $this->forms[$form->className()] = $form;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = [];
        foreach ($this->forms as $form) {
            $rules = ArrayHelper::merge($rules, $form->rules());
        }
        return $rules;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        $labels = [];
        foreach ($this->forms as $form) {
            $labels = ArrayHelper::merge($labels, $form->attributeLabels());
        }
        return $labels;
    }

    /**
     * @inheritDoc
     */
    public function getAttributes($names = null)
    {
        $attributes = parent::getAttributes();
        foreach ($this->forms as $form) {
            $attributes = ArrayHelper::merge($attributes, $form->getAttributes());
        }
        return $attributes;
    }

    /**
     * @inheritDoc
     */
    public function __get($name)
    {
        foreach ($this->forms as $form) {
            if (property_exists($form, $name)) {
                return $form->$name;
            }
        }
        return parent::__get($name);
    }

    /**
     * @inheritDoc
     */
    protected function afterValidate()
    {
        parent::afterValidate();
        foreach ($this->forms as $form) {
            if ($form->hasErrors()) {
                $this->addErrors($form->getErrors());
            }
        }
    }

    /**
     * @inheritDoc
     */
    public function __set($name, $value)
    {
        foreach ($this->forms as $form) {
            if (property_exists($form, $name)) {
                return $form->$name = $value;
            }
        }
        return parent::__set($name, $value); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function __isset($name)
    {
        if (array_key_exists($name, $this->getAttributes())) {
            return true;
        }
        return parent::__isset($name);
    }

    /**
     * @inheritDoc
     */
    protected function loadData()
    {
        if (parent::loadData() ) {
            foreach ($this->forms as $form) {
                if ($form instanceof CreateUpdateForm) {
                    $form->setActiveRecord($this->model);
                }
            }
            return true;
        }
        return false;
    }


    /**
     * @return null|User
     * @throws \CDbException
     */
    public function updateActiveRecord()
    {
        if (!$this->validate()) {
            return null;
        }
        $transaction = \Yii::app()->getDb()->beginTransaction();
        try {
            $this->internalUpdateActiveRecord();
            foreach ($this->forms as $form) {
                if ($form instanceof CreateUpdateForm) {
                    var_dump($form->ExternalId);
                    $form->isUpdateMode() ? $form->updateActiveRecord() : $form->createActiveRecord();
                }
            }
            $transaction->commit();
            return $this->model;
        } catch (\Exception $e) {
            var_dump($e->getMessage());
            $transaction->rollBack();
            Flash::setError($e);
        }
        return null;
    }

    /**
     * @return mixed
     */
    protected function internalUpdateActiveRecord() {}

    /**
     * @return null|User
     * @throws \CDbException
     */
    public function createActiveRecord()
    {
        if (!$this->validate()) {
            return null;
        }
        $transaction = \Yii::app()->getDb()->beginTransaction();
        try {
            $this->internalCreateActiveRecord();
            foreach ($this->forms as $form) {
                if ($form instanceof CreateUpdateForm) {
                    if (!$form->isUpdateMode()) {
                        $form->setActiveRecord($this->model);
                    }
                    $form->createActiveRecord();
                }
            }
            $transaction->commit();
            return $this->model;
        } catch (\Exception $e) {
            $transaction->rollBack();
            Flash::setError($e);
        }
        return null;
    }

    /**
     * @return mixed
     */
    protected function internalCreateActiveRecord() {}
}