<?php
/**
 * Created by PhpStorm.
 * User: Андрей
 * Date: 09.11.2015
 * Time: 17:44
 */

namespace partner\models\forms\user;

use application\components\form\EventItemCreateUpdateForm;
use event\models\Event;
use pay\models\OrderItem;
use pay\models\Product;
use user\models\User;

class Products extends EventItemCreateUpdateForm
{
    /** @var User */
    private $user;

    public $Products = [];

    /**
     * @param Event $event
     * @param User $user
     */
    public function __construct(Event $event, User $user)
    {
        $this->user = $user;
        parent::__construct($event, null);
    }

    /**
     * @inheritdoc
     */
    public function init()
    {
        parent::init();
        $orderItems = OrderItem::model()->byEventId($this->event->Id)->byAnyOwnerId($this->user->Id)->byPaid(true)->findAll();
        foreach ($orderItems as $orderItem) {
            if ($orderItem->Product->ManagerName) {
                $this->Products[] = $orderItem->ProductId;
            }
        }
    }

    /**
     * @return array
     */
    public function getProductData()
    {
        $products = Product::model()->byManagerName('FoodProductManager')->byEventId($this->event->Id)->findAll();
        return \CHtml::listData($products, 'Id', 'Title');
    }

    /**
     * Создает запись в базе
     * @return \CActiveRecord|null
     * @throws Exception
     */
    public function createActiveRecord()
    {
        parent::createActiveRecord(); // TODO: Change the autogenerated stub
    }
}