<?php

namespace ruvents2\components\data;

class CDbCriteria extends \CDbCriteria
{
    public static function create()
    {
        return new static();
    }

    public function setSelect($column)
    {
        $this->select = $column;
        return $this;
    }

    public function setOrder($order)
    {
        $this->order = $order;
        return $this;
    }

    public function setLimit($limit)
    {
        $this->limit = $limit;
        return $this;
    }

    public function setWith(array $with)
    {
        $this->with = $with;
        return $this;
    }

    public function mergeWith($criteria, $operator = 'AND')
    {
        parent::mergeWith($criteria, $operator); // TODO: Change the autogenerated stub
        return $this;
    }

    public function addConditionWithParams($condition, array $params = null, $operator = 'AND')
    {
        /* Добавляем условие обычным способом */
        parent::addCondition($condition, $operator);

        /* Добавляем необходимые параметры */
        $this->params = array_merge($this->params, $params);

        /* Возвращаем себя, для цепочных вызовов */
        return $this;
    }
}